### ISSUE TITLE
less doesn't compile

### ISSUE THREAD

**Issue by hackzilla** [winmarkltd/BootstrapFormHelpers#203]
I've tried to compile the less com version 2.3.0 and master and it won't compile because some images don't exist.

The offending lines are:

``` css
.bfh-flag-EUR{
  background: url(../img/eu.png) no-repeat;
}

.bfh-flag-XCD{
  background: url(../img/xcd.png) no-repeat;
}
```

If these lines are removed, then it will compile, but I can see them defined else where.
